# Generated by Django 5.0.6 on 2024-06-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_name',
        ),
    ]
