# Generated by Django 5.0.6 on 2024-06-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_imagemsg_chat_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='images',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ImageMsg',
        ),
    ]
