# Generated by Django 5.0.6 on 2024-12-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_callsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='last_read',
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
