# Generated by Django 5.0.6 on 2024-12-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='key_nonce',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userkey',
            name='master_key_salt',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
