# Generated by Django 5.0.6 on 2024-06-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, upload_to='status_images/'),
        ),
    ]
