# Generated by Django 5.0.6 on 2024-06-28 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_alter_status_options_alter_status_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='has_seen', to=settings.AUTH_USER_MODEL),
        ),
    ]
